version: '3.8'

services:
  nft-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:pass@db:5432/nft_service
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ETHEREUM_RPC_URL=https://eth-mainnet.alchemyapi.io/v2/your-key
      - POLYGON_RPC_URL=https://polygon-mainnet.alchemyapi.io/v2/your-key
      - IPFS_GATEWAY_URL=https://ipfs.io/ipfs/
      - JWT_SECRET=your-jwt-secret
    volumes:
      - ../logs:/app/logs
      - /app/node_modules
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - nft-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: nft_service
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nft-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - nft-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - nft-network

volumes:
  postgres_data:
  elasticsearch_data:

networks:
  nft-network:
    driver: bridge